name: Azure Function CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: TestACR9999.azurecr.io
        username: TestACR9999
        password: B+b/k04MW+TG6BkuoE0nic5OoJoXmQgHBtHjVyLDhU+ACRCt88FM

    - name: Build and push Docker image
      run: |
        docker build -t TestACR9999.azurecr.io/myfunctionapp:${{ github.sha }} .
        docker push TestACR9999.azurecr.io/myfunctionapp:${{ github.sha }}

  deploy-to-aks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: AKS Login
      uses: azure/aks-set-context@v1
      with:
        resource-group: AKSGroup
        cluster-name: AKSCluster1

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s-deployment.yml
